name: Configuring Static Website on S3

on:
 pull_request:
   branches:
   - main
   paths:
   - terraform/**
 push:
    branches:
      - main
    paths:
     - terraform/**
     
 permissions:
  contents: read
  pull-requests: write  # Needed for commenting on PRs

jobs:
  deploy:
    runs-on: ubuntu-latest
    with:
      terraform_wrapper: false
    env:
      AWS_REGION: eu-west-1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init
 - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        run: |
          terraform plan -no-color > tfplan.txt
          cat tfplan.txt

      - name: Comment Terraform Plan on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: tfplan.txt
          recreate: true

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var="domain_name=${{ secrets.DOMAIN_NAME }}"  -var="mail=${{ secrets.MAIL}}" -var="region=${AWS_REGION}

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var="domain_name=${{ secrets.DOMAIN_NAME }}"  -var="mail=${{ secrets.MAIL}}" -var="region=${AWS_REGION}

      - name: Upload Website Files
        run: |
          aws s3 sync site/ s3://${{ secrets.DOMAIN_NAME }}/ --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

