name: terraform-apply-on-merge

on:
  push:
    branches: [ "main" ]             # runs after you click "Merge"
    paths:
      - "terraform/**"               # only if something in terraform/ changed

permissions:
  id-token: write                     # OIDC → AWS
  contents: read

concurrency:
  group: terraform-apply-main         # avoid overlapping applies
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_ROLE}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Optional but recommended if you use an S3/DynamoDB backend
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var="domain_name=${{ secrets.DOMAIN_NAME }}"  -var="mail=${{ secrets.MAIL}}" -var="region=${{ secrets.AWS_REGION}}"
      'refs/heads/main' }}
        working-directory: terraform
        run: terraform apply -input=false -auto-approve tfplan
