name: upload-sync-site-files

on:
  push:
    branches: [ "main" ]             # runs after you click "Merge"
    paths:
      - "site/**"               # only if something in terraform/ changed

permissions:
  id-token: write                     # OIDC → AWS
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ secrets.AWS_ROLE}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Sync site/ to S3
        run: aws s3 sync site/ s3://$ {{secrets.DOMAIN_NAME}} --delete 
